/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DangKyRouteImport } from './routes/dang-ky'
import { Route as DangNhapRouteImport } from './routes/dang-nhap'
import { Route as DatHangThanhCongRouteImport } from './routes/dat-hang-thanh-cong'
import { Route as GioHangRouteImport } from './routes/gio-hang'
import { Route as TaiKhoanRouteImport } from './routes/tai-khoan'
import { Route as ThanhToanRouteImport } from './routes/thanh-toan'
import { Route as SanPhamIndexRouteImport } from './routes/san-pham.index'
import { Route as SanPhamIdRouteImport } from './routes/san-pham.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DangKyRoute = DangKyRouteImport.update({
  id: '/dang-ky',
  path: '/dang-ky',
  getParentRoute: () => rootRouteImport,
} as any)
const DangNhapRoute = DangNhapRouteImport.update({
  id: '/dang-nhap',
  path: '/dang-nhap',
  getParentRoute: () => rootRouteImport,
} as any)
const DatHangThanhCongRoute = DatHangThanhCongRouteImport.update({
  id: '/dat-hang-thanh-cong',
  path: '/dat-hang-thanh-cong',
  getParentRoute: () => rootRouteImport,
} as any)
const GioHangRoute = GioHangRouteImport.update({
  id: '/gio-hang',
  path: '/gio-hang',
  getParentRoute: () => rootRouteImport,
} as any)
const TaiKhoanRoute = TaiKhoanRouteImport.update({
  id: '/tai-khoan',
  path: '/tai-khoan',
  getParentRoute: () => rootRouteImport,
} as any)
const ThanhToanRoute = ThanhToanRouteImport.update({
  id: '/thanh-toan',
  path: '/thanh-toan',
  getParentRoute: () => rootRouteImport,
} as any)
const SanPhamIndexRoute = SanPhamIndexRouteImport.update({
  id: '/san-pham/',
  path: '/san-pham/',
  getParentRoute: () => rootRouteImport,
} as any)
const SanPhamIdRoute = SanPhamIdRouteImport.update({
  id: '/san-pham/$id',
  path: '/san-pham/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dang-ky': typeof DangKyRoute
  '/dang-nhap': typeof DangNhapRoute
  '/dat-hang-thanh-cong': typeof DatHangThanhCongRoute
  '/gio-hang': typeof GioHangRoute
  '/tai-khoan': typeof TaiKhoanRoute
  '/thanh-toan': typeof ThanhToanRoute
  '/san-pham/$id': typeof SanPhamIdRoute
  '/san-pham/': typeof SanPhamIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dang-ky': typeof DangKyRoute
  '/dang-nhap': typeof DangNhapRoute
  '/dat-hang-thanh-cong': typeof DatHangThanhCongRoute
  '/gio-hang': typeof GioHangRoute
  '/tai-khoan': typeof TaiKhoanRoute
  '/thanh-toan': typeof ThanhToanRoute
  '/san-pham/$id': typeof SanPhamIdRoute
  '/san-pham': typeof SanPhamIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dang-ky': typeof DangKyRoute
  '/dang-nhap': typeof DangNhapRoute
  '/dat-hang-thanh-cong': typeof DatHangThanhCongRoute
  '/gio-hang': typeof GioHangRoute
  '/tai-khoan': typeof TaiKhoanRoute
  '/thanh-toan': typeof ThanhToanRoute
  '/san-pham/$id': typeof SanPhamIdRoute
  '/san-pham/': typeof SanPhamIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dang-ky'
    | '/dang-nhap'
    | '/dat-hang-thanh-cong'
    | '/gio-hang'
    | '/tai-khoan'
    | '/thanh-toan'
    | '/san-pham/$id'
    | '/san-pham/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dang-ky'
    | '/dang-nhap'
    | '/dat-hang-thanh-cong'
    | '/gio-hang'
    | '/tai-khoan'
    | '/thanh-toan'
    | '/san-pham/$id'
    | '/san-pham'
  id:
    | '__root__'
    | '/'
    | '/dang-ky'
    | '/dang-nhap'
    | '/dat-hang-thanh-cong'
    | '/gio-hang'
    | '/tai-khoan'
    | '/thanh-toan'
    | '/san-pham/$id'
    | '/san-pham/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DangKyRoute: typeof DangKyRoute
  DangNhapRoute: typeof DangNhapRoute
  DatHangThanhCongRoute: typeof DatHangThanhCongRoute
  GioHangRoute: typeof GioHangRoute
  TaiKhoanRoute: typeof TaiKhoanRoute
  ThanhToanRoute: typeof ThanhToanRoute
  SanPhamIdRoute: typeof SanPhamIdRoute
  SanPhamIndexRoute: typeof SanPhamIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dang-ky': {
      id: '/dang-ky'
      path: '/dang-ky'
      fullPath: '/dang-ky'
      preLoaderRoute: typeof DangKyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dang-nhap': {
      id: '/dang-nhap'
      path: '/dang-nhap'
      fullPath: '/dang-nhap'
      preLoaderRoute: typeof DangNhapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dat-hang-thanh-cong': {
      id: '/dat-hang-thanh-cong'
      path: '/dat-hang-thanh-cong'
      fullPath: '/dat-hang-thanh-cong'
      preLoaderRoute: typeof DatHangThanhCongRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gio-hang': {
      id: '/gio-hang'
      path: '/gio-hang'
      fullPath: '/gio-hang'
      preLoaderRoute: typeof GioHangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tai-khoan': {
      id: '/tai-khoan'
      path: '/tai-khoan'
      fullPath: '/tai-khoan'
      preLoaderRoute: typeof TaiKhoanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thanh-toan': {
      id: '/thanh-toan'
      path: '/thanh-toan'
      fullPath: '/thanh-toan'
      preLoaderRoute: typeof ThanhToanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/san-pham/': {
      id: '/san-pham/'
      path: '/san-pham'
      fullPath: '/san-pham/'
      preLoaderRoute: typeof SanPhamIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/san-pham/$id': {
      id: '/san-pham/$id'
      path: '/san-pham/$id'
      fullPath: '/san-pham/$id'
      preLoaderRoute: typeof SanPhamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DangKyRoute: DangKyRoute,
  DangNhapRoute: DangNhapRoute,
  DatHangThanhCongRoute: DatHangThanhCongRoute,
  GioHangRoute: GioHangRoute,
  TaiKhoanRoute: TaiKhoanRoute,
  ThanhToanRoute: ThanhToanRoute,
  SanPhamIdRoute: SanPhamIdRoute,
  SanPhamIndexRoute: SanPhamIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
